{
  "user_service": {
    "timestamp": "2025-05-15T09:34:10.907817",
    "status": "healthy",
    "response_time": 0.009656
  },
  "order_service": {
    "timestamp": "2025-05-15T09:34:10.907817",
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_b', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffaa9aec40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
  },
  "inventory_service": {
    "timestamp": "2025-05-15T09:34:10.907817",
    "status": "healthy",
    "response_time": 0.002077
  },
  "notification_service": {
    "timestamp": "2025-05-15T09:34:10.907817",
    "status": "healthy",
    "response_time": 0.003073
  }
}